version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 5.2.4.5
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: brakeman
    versions:
    - 5.0.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: capistrano
    versions:
    - 3.15.0
  - dependency-name: breadcrumbs_on_rails
    versions:
    - 4.0.0
  - dependency-name: tinymce-rails
    versions:
    - 5.6.2.1
