language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
script: bundle exec rspec spec
before_script:
  - psql -c 'create database rulebook_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
