require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppConfigsController do
  before (:each) do
    @admin_user = FactoryGirl.create(:admin_user)
    sign_in @admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # AppConfig. As you add validations to AppConfig, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { rulebook_name: "My Rulebook",
      front_page: "Something Interesting",
      faq: "FAQ lives here",
      copyright: "Teh new Copyright"
    }
  end

  describe "GET index" do
    it "assigns all app_configs as @app_configs" do
      app_config = AppConfig.create! valid_attributes
      get :index, {}
      assigns(:app_configs).should eq([app_config])
    end
  end

  describe "GET show" do
    it "assigns the requested app_config as @app_config" do
      app_config = AppConfig.create! valid_attributes
      get :show, {:id => app_config.to_param}
      assigns(:app_config).should eq(app_config)
    end
  end

  describe "GET new" do
    it "assigns a new app_config as @app_config" do
      get :new, {}
      assigns(:app_config).should be_a_new(AppConfig)
    end
  end

  describe "GET edit" do
    it "assigns the requested app_config as @app_config" do
      app_config = AppConfig.create! valid_attributes
      get :edit, {:id => app_config.to_param}
      assigns(:app_config).should eq(app_config)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppConfig" do
        expect {
          post :create, {:app_config => valid_attributes}
        }.to change(AppConfig, :count).by(1)
      end

      it "assigns a newly created app_config as @app_config" do
        post :create, {:app_config => valid_attributes}
        assigns(:app_config).should be_a(AppConfig)
        assigns(:app_config).should be_persisted
      end

      it "redirects to the created app_config" do
        post :create, {:app_config => valid_attributes}
        response.should redirect_to(AppConfig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved app_config as @app_config" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppConfig.any_instance.stub(:save).and_return(false)
        post :create, {:app_config => {rulebook_name: 'the book'}}
        assigns(:app_config).should be_a_new(AppConfig)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppConfig.any_instance.stub(:save).and_return(false)
        post :create, {:app_config => {rulebook_name: 'the book'}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested app_config" do
        app_config = AppConfig.create! valid_attributes
        # Assuming there are no other app_configs in the database, this
        # specifies that the AppConfig created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AppConfig.any_instance.should_receive(:update_attributes).with({})
        put :update, {:id => app_config.to_param, :app_config => {'these' => 'params'}}
      end

      it "assigns the requested app_config as @app_config" do
        app_config = AppConfig.create! valid_attributes
        put :update, {:id => app_config.to_param, :app_config => valid_attributes}
        assigns(:app_config).should eq(app_config)
      end

      it "redirects to the app_config" do
        app_config = AppConfig.create! valid_attributes
        put :update, {:id => app_config.to_param, :app_config => valid_attributes}
        response.should redirect_to(app_config)
      end
    end

    describe "with invalid params" do
      it "assigns the app_config as @app_config" do
        app_config = AppConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_config.to_param, :app_config => {rulebook_name: 'the book'}}
        assigns(:app_config).should eq(app_config)
      end

      it "re-renders the 'edit' template" do
        app_config = AppConfig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppConfig.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_config.to_param, :app_config => {rulebook_name: 'the book'}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested app_config" do
      app_config = AppConfig.create! valid_attributes
      expect {
        delete :destroy, {:id => app_config.to_param}
      }.to change(AppConfig, :count).by(-1)
    end

    it "redirects to the app_configs list" do
      app_config = AppConfig.create! valid_attributes
      delete :destroy, {:id => app_config.to_param}
      response.should redirect_to(app_configs_url)
    end
  end

end
