require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentsController do
  before(:each) do
    ActionMailer::Base.deliveries.clear

    @proposal = FactoryGirl.create(:proposal)

    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { comment: "hi"}
  end
  
  describe "GET index" do
    it "assigns all comments as @comments" do
      comment = FactoryGirl.create(:comment, :proposal => @proposal)
      get :index, {:proposal_id => @proposal.id}
      assigns(:comments).should eq([comment])
    end
  end

  describe "GET show" do
    it "assigns the requested comment as @comment" do
      comment = FactoryGirl.create(:comment, :proposal => @proposal)
      get :show, {:id => comment.to_param, :proposal_id => @proposal.id}
      assigns(:comment).should eq(comment)
    end
  end

  describe "GET new" do
    it "assigns a new comment as @comment" do
      get :new, {:proposal_id => @proposal.id}
      assigns(:comment).should be_a_new(Comment)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment as @comment" do
      comment = FactoryGirl.create(:comment, :proposal => @proposal)
      get :edit, {:id => comment.to_param, :proposal_id => @proposal.id}
      assigns(:comment).should eq(comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comment" do
        expect {
          post :create, {:comment => valid_attributes, :proposal_id => @proposal.id}
        }.to change(Comment, :count).by(1)
      end

      it "assigns a newly created comment as @comment" do
        post :create, {:comment => valid_attributes, :proposal_id => @proposal.id}
        assigns(:comment).should be_a(Comment)
        assigns(:comment).should be_persisted
      end

      it "redirects to the created comment" do
        post :create, {:comment => valid_attributes, :proposal_id => @proposal.id}
        response.should redirect_to([@proposal, Comment.last])
      end

      it "sends an e-mail" do
        post :create, {:comment => valid_attributes, :proposal_id => @proposal.id}
        num_deliveries = ActionMailer::Base.deliveries.size
        num_deliveries.should == 1
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment as @comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, {:comment => {}, :proposal_id => @proposal.id}
        assigns(:comment).should be_a_new(Comment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, {:comment => {}, :proposal_id => @proposal.id}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment" do
        comment = FactoryGirl.create(:comment, :proposal => @proposal)
        # Assuming there are no other comments in the database, this
        # specifies that the Comment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comment.to_param, :comment => {'these' => 'params'}, :proposal_id => @proposal.id}
      end

      it "assigns the requested comment as @comment" do
        comment = FactoryGirl.create(:comment, :proposal => @proposal)
        put :update, {:id => comment.to_param, :comment => valid_attributes, :proposal_id => @proposal.id}
        assigns(:comment).should eq(comment)
      end

      it "redirects to the comment" do
        comment = FactoryGirl.create(:comment, :proposal => @proposal)
        put :update, {:id => comment.to_param, :comment => valid_attributes, :proposal_id => @proposal.id}
        response.should redirect_to([@proposal, comment])
      end
    end

    describe "with invalid params" do
      it "assigns the comment as @comment" do
        comment = FactoryGirl.create(:comment, :proposal => @proposal)
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment.to_param, :comment => {}, :proposal_id => @proposal.id}
        assigns(:comment).should eq(comment)
      end

      it "re-renders the 'edit' template" do
        comment = FactoryGirl.create(:comment, :proposal => @proposal)
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment.to_param, :comment => {}, :proposal_id => @proposal.id}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment" do
      comment = FactoryGirl.create(:comment, :proposal => @proposal)
      expect {
        delete :destroy, {:id => comment.to_param, :proposal_id => @proposal.id}
      }.to change(Comment, :count).by(-1)
    end

    it "redirects to the comments list" do
      comment = FactoryGirl.create(:comment, :proposal => @proposal)
      delete :destroy, {:id => comment.to_param, :proposal_id => @proposal.id}
      response.should redirect_to(@proposal)
    end
  end

end
