# == Schema Information
#
# Table name: committees
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  preliminary :boolean          default(TRUE), not null
#

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommitteesController, type: :controller do
  before (:each) do
    @user = FactoryGirl.create(:user)
    @admin_user = FactoryGirl.create(:admin_user)
    sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # Event. As you add validations to Event, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { name: "MyName",
      preliminary: false}
  end

  describe "GET index" do
    it "fails when not logged in" do
      sign_out @user
      get :index
      expect(response).to redirect_to(new_user_session_path)
    end
    describe "for a committee_admin" do
      before(:each) do
        @committee_admin = FactoryGirl.create(:user)
        @cm = FactoryGirl.create(:committee_member, admin: true, user: @committee_admin)
        sign_out @user
        sign_in @committee_admin
      end
      it "succeeds for committee_admin" do
        get :index
        expect(response).to be_success
      end
      it "only shows MY committees" do
        get :index
        expect(assigns(:committees)).to eq([@cm.committee])
      end
    end

    it "assigns all committees as @committees when admin user" do
      sign_out @user
      sign_in @admin_user
      committee = Committee.create! valid_attributes
      get :index
      expect(assigns(:committees)).to eq([committee])
    end
  end

  describe "GET show" do
    describe "when not signed in" do
      before(:each) do
        sign_out @user
      end

      it "should show all proposals that are not 'Submitted'" do
        # @proposal is 'Submitted'
        committee = FactoryGirl.create(:committee)
        proposal = FactoryGirl.create(:proposal, status: 'Review', committee: committee)
        get :show, params: { id: committee.id }
        expect(assigns(:proposals)).to eq([proposal])
      end
    end
  end

  describe "GET new" do
    it "assigns a new committee as @committee" do
      sign_out @user
      sign_in @admin_user
      get :new
      expect(assigns(:committee)).to be_a_new(Committee)
    end
  end

  describe "GET edit" do
    it "assigns the requested committee as @committee" do
      sign_out @user
      sign_in @admin_user
      committee = Committee.create! valid_attributes
      get :edit, params: {id: committee.to_param}
      expect(assigns(:committee)).to eq(committee)
    end
  end

  describe "POST create" do
    before (:each) do
      sign_out @user
      sign_in @admin_user
    end
    describe "with valid params" do
      it "creates a new Committee" do
        expect {
          post :create, params: {committee: valid_attributes}
        }.to change(Committee, :count).by(1)
      end

      it "assigns a newly created committee as @committee" do
        post :create, params: {committee: valid_attributes}
        expect(assigns(:committee)).to be_a(Committee)
        expect(assigns(:committee)).to be_persisted
      end

      it "redirects to the created committee" do
        post :create, params: {committee: valid_attributes}
        expect(response).to redirect_to(committees_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved committee as @committee" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Committee).to receive(:save).and_return(false)
        post :create, params: {committee: {name: 'fake'}}
        expect(assigns(:committee)).to be_a_new(Committee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Committee).to receive(:save).and_return(false)
        post :create, params: {committee: {name: 'fake'}}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    before (:each) do
      sign_out @user
      sign_in @admin_user
    end
    describe "with valid params" do
      it "assigns the requested committee as @committee" do
        committee = Committee.create! valid_attributes
        put :update, params: {id: committee.to_param, committee: valid_attributes}
        expect(assigns(:committee)).to eq(committee)
      end

      it "redirects to the committee" do
        committee = Committee.create! valid_attributes
        put :update, params: {id: committee.to_param, committee: valid_attributes}
        expect(response).to redirect_to(committees_path)
      end
    end

    describe "with invalid params" do
      it "assigns the committee as @committee" do
        committee = Committee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Committee).to receive(:save).and_return(false)
        put :update, params: {id: committee.to_param, committee: {name: 'fake'}}
        expect(assigns(:committee)).to eq(committee)
      end

      it "re-renders the 'edit' template" do
        committee = Committee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Committee).to receive(:save).and_return(false)
        put :update, params: {id: committee.to_param, committee: {name: 'fake'}}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    before (:each) do
      sign_out @user
      sign_in @admin_user
    end
    it "destroys the requested committee" do
      committee = Committee.create! valid_attributes
      expect {
        delete :destroy, params: {id: committee.to_param}
      }.to change(Committee, :count).by(-1)
    end

    it "redirects to the committee list" do
      committee = Committee.create! valid_attributes
      delete :destroy, params: {id: committee.to_param}
      expect(response).to redirect_to(committees_url)
    end
  end

  describe "GET membership" do
    it "assigns all committees as @committees" do
      committee = FactoryGirl.create(:committee)
      get :membership
      expect(response).to be_success
      expect(assigns(:committees)).to eq([committee])
    end
    it "should assign all users as @users" do
      get :membership
      expect(response).to be_success
      expect(assigns(:users)).to match_array([@user, @admin_user])
    end
  end
end
