require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RevisionsController do
  before(:each) do
    @admin = FactoryGirl.create(:admin_user)
    sign_in @admin
  end

  # This should return the minimal set of attributes required to create a valid
  # Revision. As you add validations to Revision, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { body: "blah",
      change_description: "blaa"}
  end
  
  describe "GET index" do
    it "assigns all revisions as @revisions" do
      revision = Revision.create! valid_attributes
      get :index, {}
      assigns(:revisions).should eq([revision])
    end
  end

  describe "GET show" do
    it "assigns the requested revision as @revision" do
      revision = Revision.create! valid_attributes
      get :show, {:id => revision.to_param}
      assigns(:revision).should eq(revision)
    end
  end

  describe "GET new" do
    it "assigns a new revision as @revision" do
      get :new, {}
      assigns(:revision).should be_a_new(Revision)
    end
  end

  describe "GET edit" do
    it "assigns the requested revision as @revision" do
      revision = Revision.create! valid_attributes
      get :edit, {:id => revision.to_param}
      assigns(:revision).should eq(revision)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Revision" do
        expect {
          post :create, {:revision => valid_attributes}
        }.to change(Revision, :count).by(1)
      end

      it "assigns a newly created revision as @revision" do
        post :create, {:revision => valid_attributes}
        assigns(:revision).should be_a(Revision)
        assigns(:revision).should be_persisted
      end

      it "redirects to the created revision" do
        post :create, {:revision => valid_attributes}
        response.should redirect_to(Revision.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved revision as @revision" do
        # Trigger the behavior that occurs when invalid params are submitted
        Revision.any_instance.stub(:save).and_return(false)
        post :create, {:revision => {}}
        assigns(:revision).should be_a_new(Revision)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Revision.any_instance.stub(:save).and_return(false)
        post :create, {:revision => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested revision" do
        revision = Revision.create! valid_attributes
        # Assuming there are no other revisions in the database, this
        # specifies that the Revision created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Revision.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => revision.to_param, :revision => {'these' => 'params'}}
      end

      it "assigns the requested revision as @revision" do
        revision = Revision.create! valid_attributes
        put :update, {:id => revision.to_param, :revision => valid_attributes}
        assigns(:revision).should eq(revision)
      end

      it "redirects to the revision" do
        revision = Revision.create! valid_attributes
        put :update, {:id => revision.to_param, :revision => valid_attributes}
        response.should redirect_to(revision)
      end
    end

    describe "with invalid params" do
      it "assigns the revision as @revision" do
        revision = Revision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Revision.any_instance.stub(:save).and_return(false)
        put :update, {:id => revision.to_param, :revision => {}}
        assigns(:revision).should eq(revision)
      end

      it "re-renders the 'edit' template" do
        revision = Revision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Revision.any_instance.stub(:save).and_return(false)
        put :update, {:id => revision.to_param, :revision => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested revision" do
      revision = Revision.create! valid_attributes
      expect {
        delete :destroy, {:id => revision.to_param}
      }.to change(Revision, :count).by(-1)
    end

    it "redirects to the revisions list" do
      revision = Revision.create! valid_attributes
      delete :destroy, {:id => revision.to_param}
      response.should redirect_to(revisions_url)
    end
  end

end
