require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RulebooksController, :type => :controller do
  before (:each) do
    @admin_user = FactoryGirl.create(:admin_user)
    sign_in @admin_user
  end

  # This should return the minimal set of attributes required to create a valid
  # Rulebook. As you add validations to Rulebook, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { rulebook_name: "My Rulebook",
      front_page: "Something Interesting",
      faq: "FAQ lives here",
      copyright: "Teh new Copyright"
    }
  end

  describe "GET index" do
    it "assigns all rulebooks as @rulebooks" do
      rulebook = Rulebook.create! valid_attributes
      get :index, {}
      expect(assigns(:rulebooks)).to eq([rulebook])
    end
  end

  describe "GET show" do
    it "assigns the requested rulebook as @rulebook" do
      rulebook = Rulebook.create! valid_attributes
      get :show, {:id => rulebook.to_param}
      expect(assigns(:rulebook)).to eq(rulebook)
    end
  end

  describe "GET new" do
    it "assigns a new rulebook as @rulebook" do
      get :new, {}
      expect(assigns(:rulebook)).to be_a_new(Rulebook)
    end
  end

  describe "GET edit" do
    it "assigns the requested rulebook as @rulebook" do
      rulebook = Rulebook.create! valid_attributes
      get :edit, {:id => rulebook.to_param}
      expect(assigns(:rulebook)).to eq(rulebook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rulebook" do
        expect {
          post :create, {:rulebook => valid_attributes}
        }.to change(Rulebook, :count).by(1)
      end

      it "assigns a newly created rulebook as @rulebook" do
        post :create, {:rulebook => valid_attributes}
        expect(assigns(:rulebook)).to be_a(Rulebook)
        expect(assigns(:rulebook)).to be_persisted
      end

      it "redirects to the created rulebook" do
        post :create, {:rulebook => valid_attributes}
        expect(response).to redirect_to(Rulebook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rulebook as @rulebook" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Rulebook).to receive(:save).and_return(false)
        post :create, {:rulebook => {rulebook_name: 'the book'}}
        expect(assigns(:rulebook)).to be_a_new(Rulebook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Rulebook).to receive(:save).and_return(false)
        post :create, {:rulebook => {rulebook_name: 'the book'}}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rulebook" do
        rulebook = Rulebook.create! valid_attributes
        # Assuming there are no other rulebooks in the database, this
        # specifies that the Rulebook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Rulebook).to receive(:update_attributes).with({})
        put :update, {:id => rulebook.to_param, :rulebook => {'these' => 'params'}}
      end

      it "assigns the requested rulebook as @rulebook" do
        rulebook = Rulebook.create! valid_attributes
        put :update, {:id => rulebook.to_param, :rulebook => valid_attributes}
        expect(assigns(:rulebook)).to eq(rulebook)
      end

      it "redirects to the rulebook" do
        rulebook = Rulebook.create! valid_attributes
        put :update, {:id => rulebook.to_param, :rulebook => valid_attributes}
        expect(response).to redirect_to(rulebook)
      end
    end

    describe "with invalid params" do
      it "assigns the rulebook as @rulebook" do
        rulebook = Rulebook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Rulebook).to receive(:save).and_return(false)
        put :update, {:id => rulebook.to_param, :rulebook => {rulebook_name: 'the book'}}
        expect(assigns(:rulebook)).to eq(rulebook)
      end

      it "re-renders the 'edit' template" do
        rulebook = Rulebook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Rulebook).to receive(:save).and_return(false)
        put :update, {:id => rulebook.to_param, :rulebook => {rulebook_name: 'the book'}}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rulebook" do
      rulebook = Rulebook.create! valid_attributes
      expect {
        delete :destroy, {:id => rulebook.to_param}
      }.to change(Rulebook, :count).by(-1)
    end

    it "redirects to the rulebooks list" do
      rulebook = Rulebook.create! valid_attributes
      delete :destroy, {:id => rulebook.to_param}
      expect(response).to redirect_to(rulebooks_url)
    end
  end

end
